/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernorCountingSimple } from "./GovernorCountingSimple";
export type { GovernorVotes } from "./GovernorVotes";
export type { GovernorVotesQuorumFraction } from "./GovernorVotesQuorumFraction";
