/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorCountingSimple__factory } from "./GovernorCountingSimple__factory";
export { GovernorVotes__factory } from "./GovernorVotes__factory";
export { GovernorVotesQuorumFraction__factory } from "./GovernorVotesQuorumFraction__factory";
